apiVersion: v1
kind: Service
metadata:
  name: mirror-maestro
  namespace: mirror-maestro
  labels:
    app.kubernetes.io/name: mirror-maestro
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mirror-maestro
    app.kubernetes.io/component: app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
